# Generated by Django 2.1.7 on 2019-02-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0009_auto_20190222_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('dwell_time', models.FloatField(default=200, verbose_name='dwell time (s)')),
                ('start_time', models.FloatField(blank=True, null=True, verbose_name='start time (s)')),
                ('end_time', models.FloatField(blank=True, null=True, verbose_name='end time (s)')),
                ('current', models.FloatField(default=40, verbose_name='Current (A)')),
                ('main_gas_flow', models.FloatField(default=0, verbose_name='main gas flow (g/s)')),
                ('shield_gas_flow', models.FloatField(default=0, verbose_name='shield gas flow (g/s)')),
                ('purge_gas_flow', models.FloatField(default=0, verbose_name='purge gas flow (g/s)')),
                ('nozzle_distance', models.FloatField(default=6, verbose_name='nozzle distance (cm)')),
                ('swivel_sting_duration', models.FloatField(default=0, verbose_name='swivel sting duration (s)')),
                ('L1_sting_duration', models.FloatField(default=0, verbose_name='L1 sting duration (s)')),
                ('L2_sting_duration', models.FloatField(default=0, verbose_name='L2 sting duration (s)')),
            ],
        ),
        migrations.CreateModel(
            name='DistilledWaterLoop',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Run')),
                ('temperature', models.FloatField(null=True, verbose_name='HCW-ST-101 Temp (F)')),
                ('conductivity', models.FloatField(null=True, verbose_name='HCW-ST-101 Conduct. (mS)')),
                ('arc_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-130 Arc supply (PSIG)')),
                ('arc_return_pressure', models.FloatField(null=True, verbose_name='HCW-PI-133 Arc return (PSIG)')),
                ('spare_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-140 Spare supply (PSIG)')),
                ('spare_return_pressure', models.FloatField(null=True, verbose_name='HCW-PI-146 Spare return (PSIG)')),
                ('chamber_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-147 Chamber supply (PSIG)')),
            ],
        ),
        migrations.CreateModel(
            name='FileAttachments',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Run')),
                ('run_sheet', models.FileField(blank=True, null=True, upload_to='')),
                ('pretest_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('posttest_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbrv', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'gases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GasSettings',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Run')),
                ('main_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_gas', to='system.Gas')),
                ('purge_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purge_gas', to='system.Gas')),
                ('shield_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shield_gas', to='system.Gas')),
            ],
        ),
        migrations.CreateModel(
            name='HeaterSettings',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Run')),
                ('nozzle_exit_diameter', models.FloatField(null=True, verbose_name='nozzle exit diameter (cm)')),
                ('total_cathode_time', models.FloatField(null=True, verbose_name='total cathode time (s)')),
                ('total_arc_on_duration', models.FloatField(null=True, verbose_name='total arc-on duration (s)')),
                ('number_disks', models.PositiveSmallIntegerField(default=3, null=True)),
                ('number_cathode_starts', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorWaterLoop',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Run')),
                ('temperature', models.FloatField(null=True, verbose_name='HCW-ST-101 Temp (F)')),
                ('conductivity', models.FloatField(null=True, verbose_name='HCW-ST-101 Conduct. (mS)')),
                ('arc_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-130 Arc supply (PSIG)')),
                ('arc_return_pressure', models.FloatField(null=True, verbose_name='HCW-PI-133 Arc return (PSIG)')),
                ('spare_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-140 Spare supply (PSIG)')),
                ('spare_return_pressure', models.FloatField(null=True, verbose_name='HCW-PI-146 Spare return (PSIG)')),
                ('chamber_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-147 Chamber supply (PSIG)')),
            ],
        ),
        migrations.CreateModel(
            name='StingDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sn', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('limits', models.CharField(max_length=200)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StingSettings',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Run')),
                ('L1_sting_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='L1', to='system.StingDevice')),
                ('L2_sting_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='L2', to='system.StingDevice')),
                ('swivel_sting_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stingsw', to='system.StingDevice')),
            ],
        ),
        migrations.CreateModel(
            name='VacuumWaterLoop',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Run')),
                ('temperature', models.FloatField(null=True, verbose_name='HCW-ST-101 Temp (F)')),
                ('conductivity', models.FloatField(null=True, verbose_name='HCW-ST-101 Conduct. (mS)')),
                ('arc_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-130 Arc supply (PSIG)')),
                ('arc_return_pressure', models.FloatField(null=True, verbose_name='HCW-PI-133 Arc return (PSIG)')),
                ('spare_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-140 Spare supply (PSIG)')),
                ('spare_return_pressure', models.FloatField(null=True, verbose_name='HCW-PI-146 Spare return (PSIG)')),
                ('chamber_supply_pressure', models.FloatField(null=True, verbose_name='HCW-PI-147 Chamber supply (PSIG)')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run'),
        ),
    ]
