# Generated by Django 2.1.7 on 2019-02-23 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20190222_2332'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacuumSystem',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Run')),
                ('pump_base_pressure', models.FloatField(null=True, verbose_name='pump base pressure GS-PI-381 (torr)')),
                ('chamber_no_purge_pressure', models.FloatField(null=True, verbose_name='chamber no-purge pressure GS-PI-374 (torr)')),
                ('chamber_purge_pressure', models.FloatField(null=True, verbose_name='chamber purge pressure (torr)')),
                ('chamber_posttest_pressure', models.FloatField(null=True, verbose_name='chamber posttest pressure (torr)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fileattachments',
            options={'verbose_name_plural': 'file attachments'},
        ),
        migrations.AlterModelOptions(
            name='gassettings',
            options={'verbose_name_plural': 'gas settings'},
        ),
        migrations.AlterModelOptions(
            name='heatersettings',
            options={'verbose_name_plural': 'heater settings'},
        ),
        migrations.AlterModelOptions(
            name='stingsettings',
            options={'verbose_name_plural': 'sting settings'},
        ),
        migrations.AddField(
            model_name='gassettings',
            name='main_gas_final_pressure',
            field=models.FloatField(null=True, verbose_name='main gas final pressure (PSIG)'),
        ),
        migrations.AddField(
            model_name='gassettings',
            name='main_gas_initial_pressure',
            field=models.FloatField(null=True, verbose_name='main gas initial pressure (PSIG)'),
        ),
        migrations.AddField(
            model_name='gassettings',
            name='purge_gas_final_pressure',
            field=models.FloatField(null=True, verbose_name='purge gas final pressure (PSIG)'),
        ),
        migrations.AddField(
            model_name='gassettings',
            name='purge_gas_initial_pressure',
            field=models.FloatField(null=True, verbose_name='purge gas initial pressure (PSIG)'),
        ),
        migrations.AddField(
            model_name='gassettings',
            name='shield_gas_final_pressure',
            field=models.FloatField(null=True, verbose_name='shield gas final pressure (PSIG)'),
        ),
        migrations.AddField(
            model_name='gassettings',
            name='shield_gas_initial_pressure',
            field=models.FloatField(null=True, verbose_name='shield gas initial pressure (PSIG)'),
        ),
    ]
