# Generated by Django 2.1.7 on 2019-02-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190223_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gassettings',
            name='main_gas_final_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='main gas final pressure (PSIG)'),
        ),
        migrations.AlterField(
            model_name='gassettings',
            name='main_gas_initial_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='main gas initial pressure (PSIG)'),
        ),
        migrations.AlterField(
            model_name='gassettings',
            name='purge_gas_final_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='purge gas final pressure (PSIG)'),
        ),
        migrations.AlterField(
            model_name='gassettings',
            name='purge_gas_initial_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='purge gas initial pressure (PSIG)'),
        ),
        migrations.AlterField(
            model_name='gassettings',
            name='shield_gas_final_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='shield gas final pressure (PSIG)'),
        ),
        migrations.AlterField(
            model_name='gassettings',
            name='shield_gas_initial_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='shield gas initial pressure (PSIG)'),
        ),
    ]
