# Generated by Django 2.1.1 on 2019-08-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20190223_0105'),
        ('system', '0003_auto_20190225_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dwell_time', models.FloatField(default=200, verbose_name='dwell time (s)')),
                ('start_time', models.FloatField(blank=True, null=True, verbose_name='start time (s)')),
                ('end_time', models.FloatField(blank=True, null=True, verbose_name='end time (s)')),
            ],
        ),
        migrations.CreateModel(
            name='StingInsertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swivel_sting_duration', models.FloatField(default=0, verbose_name='swivel sting duration (s)')),
                ('L1_sting_duration', models.FloatField(default=0, verbose_name='L1 sting duration (s)')),
                ('L2_sting_duration', models.FloatField(default=0, verbose_name='L2 sting duration (s)')),
            ],
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='purge_gas_flow',
            new_name='plasma_gas_flow',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='L1_sting_duration',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='L2_sting_duration',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dwell_time',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='nozzle_distance',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='run',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='swivel_sting_duration',
        ),
        migrations.RemoveField(
            model_name='gassettings',
            name='main_gas',
        ),
        migrations.RemoveField(
            model_name='gassettings',
            name='main_gas_final_pressure',
        ),
        migrations.RemoveField(
            model_name='gassettings',
            name='main_gas_initial_pressure',
        ),
        migrations.AddField(
            model_name='condition',
            name='nozzle_diameter',
            field=models.FloatField(default=1, verbose_name='nozzle diameter (cm)'),
        ),
        migrations.AddField(
            model_name='condition',
            name='plasma_gas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plasma_gas', to='system.Gas'),
        ),
        migrations.AddField(
            model_name='condition',
            name='shield_gas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shield_gas', to='system.Gas'),
        ),
        migrations.AddField(
            model_name='gassettings',
            name='plasma_gas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plasma_gas', to='system.Gas'),
        ),
        migrations.AddField(
            model_name='gassettings',
            name='plasma_gas_final_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='plasma gas final pressure (PSIG)'),
        ),
        migrations.AddField(
            model_name='gassettings',
            name='plasma_gas_initial_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='plasma gas initial pressure (PSIG)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Condition'),
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run'),
        ),
    ]
