# Generated by Django 2.1.7 on 2019-09-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20190827_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='main_gas_flow',
        ),
        migrations.AlterField(
            model_name='condition',
            name='plasma_gas_flow',
            field=models.FloatField(default=0, verbose_name='plasma gas flow (g/s)'),
        ),
    ]
