# Generated by Django 2.1.7 on 2019-09-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190917_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorwaterloop',
            name='arc_return_pressure',
        ),
        migrations.RemoveField(
            model_name='sensorwaterloop',
            name='chamber_supply_pressure',
        ),
        migrations.RemoveField(
            model_name='sensorwaterloop',
            name='spare_return_pressure',
        ),
        migrations.RemoveField(
            model_name='sensorwaterloop',
            name='spare_supply_pressure',
        ),
        migrations.RemoveField(
            model_name='vacuumwaterloop',
            name='arc_return_pressure',
        ),
        migrations.RemoveField(
            model_name='vacuumwaterloop',
            name='arc_supply_pressure',
        ),
        migrations.RemoveField(
            model_name='vacuumwaterloop',
            name='chamber_supply_pressure',
        ),
        migrations.RemoveField(
            model_name='vacuumwaterloop',
            name='conductivity',
        ),
        migrations.RemoveField(
            model_name='vacuumwaterloop',
            name='spare_return_pressure',
        ),
        migrations.RemoveField(
            model_name='vacuumwaterloop',
            name='spare_supply_pressure',
        ),
        migrations.RemoveField(
            model_name='vacuumwaterloop',
            name='temperature',
        ),
        migrations.AddField(
            model_name='vacuumwaterloop',
            name='ex_flow',
            field=models.FloatField(null=True, verbose_name='VPW-FI-220 heat ex. Press (GPM)'),
        ),
        migrations.AddField(
            model_name='vacuumwaterloop',
            name='ex_pressure',
            field=models.FloatField(null=True, verbose_name='VPW-PI-220 heat ex. Press (PSIG)'),
        ),
        migrations.AddField(
            model_name='vacuumwaterloop',
            name='vac_exit_temperature',
            field=models.FloatField(null=True, verbose_name='VPW-TI-280 vac. pump exit T (F)'),
        ),
        migrations.AddField(
            model_name='vacuumwaterloop',
            name='vac_flow',
            field=models.FloatField(null=True, verbose_name='VPW-FI-230 vac. pump Flow (GPM)'),
        ),
        migrations.AddField(
            model_name='vacuumwaterloop',
            name='vac_pressure',
            field=models.FloatField(null=True, verbose_name='VPW-PI-230 vac. pump Press. (PSIG)'),
        ),
        migrations.AlterField(
            model_name='heatersettings',
            name='number_disks',
            field=models.PositiveSmallIntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='sensorwaterloop',
            name='arc_supply_pressure',
            field=models.FloatField(null=True, verbose_name='SKW-PI-440 sensor supply (PSIG)'),
        ),
        migrations.AlterField(
            model_name='sensorwaterloop',
            name='conductivity',
            field=models.FloatField(null=True, verbose_name='SKW-ST-401 Conduct. (uS)'),
        ),
        migrations.AlterField(
            model_name='sensorwaterloop',
            name='temperature',
            field=models.FloatField(null=True, verbose_name='SKW-TI-401 Temp (F)'),
        ),
    ]
