# Generated by Django 2.1.7 on 2019-10-30 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190917_1734'),
        ('system', '0007_auto_20191030_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CameraPosition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.CameraPosition')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('diameter', models.FloatField(null=True, verbose_name='Diameter (cm)')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpticalFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run')),
            ],
            options={
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='condition',
            name='nozzle_diameter',
        ),
        migrations.RemoveField(
            model_name='heatersettings',
            name='nozzle_exit_diameter',
        ),
        migrations.AlterField(
            model_name='condition',
            name='plasma_gas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plasma_gas', to='system.Gas'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='shield_gas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shield_gas', to='system.Gas'),
        ),
        migrations.AlterField(
            model_name='conditioninstance',
            name='dwell_time',
            field=models.FloatField(blank=True, default=60, null=True, verbose_name='dwell time (s)'),
        ),
        migrations.AlterField(
            model_name='conditioninstance',
            name='end_time',
            field=models.FloatField(null=True, verbose_name='end time (s)'),
        ),
        migrations.AlterField(
            model_name='conditioninstance',
            name='start_time',
            field=models.FloatField(null=True, verbose_name='start time (s)'),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='lens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Lens'),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='opticalfilter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.OpticalFilter'),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run'),
        ),
        migrations.AddField(
            model_name='condition',
            name='nozzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Nozzle', to='system.Nozzle'),
        ),
        migrations.AddField(
            model_name='heatersettings',
            name='nozzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Nozzle'),
        ),
    ]
