# Generated by Django 2.1.11 on 2019-12-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20191030_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StingArm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name_plural': 'lenses'},
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='diameter',
            field=models.FloatField(null=True, verbose_name='Diameter (inch)'),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
