# Generated by Django 2.1.11 on 2020-09-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20191030_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name_plural': 'lenses'},
        ),
    ]
