# Generated by Django 2.1.7 on 2019-11-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190917_1734'),
        ('system', '0009_auto_20191031_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('dateInstalled', models.DateField(blank=True, null=True)),
                ('dateRemoved', models.DateField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True, verbose_name='Cathode time (s)')),
                ('notes', models.TextField(null=True)),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Apparatus')),
            ],
        ),
    ]
