# Generated by Django 2.1.11 on 2020-11-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20201106_1429'),
        ('system', '0009_auto_20200915_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreRunSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(null=True)),
                ('procedure', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('DOC', 'Document'), ('IMG', 'Image'), ('VID', 'Video'), ('OTR', 'Other')], default='DOC', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run')),
            ],
            options={
                'verbose_name_plural': 'file attachment',
            },
        ),
        migrations.CreateModel(
            name='StingArm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stingsettings',
            name='L1_sting_arm',
        ),
        migrations.RemoveField(
            model_name='stingsettings',
            name='L2_sting_arm',
        ),
        migrations.RemoveField(
            model_name='stingsettings',
            name='run',
        ),
        migrations.RemoveField(
            model_name='stingsettings',
            name='swivel_sting_arm',
        ),
        migrations.RenameField(
            model_name='stingdevice',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='stingdevice',
            name='limits',
        ),
        migrations.RemoveField(
            model_name='stingdevice',
            name='size',
        ),
        migrations.RemoveField(
            model_name='stingdevice',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='stinginsertion',
            name='L1_sting_duration',
        ),
        migrations.RemoveField(
            model_name='stinginsertion',
            name='L2_sting_duration',
        ),
        migrations.RemoveField(
            model_name='stinginsertion',
            name='swivel_sting_duration',
        ),
        migrations.AddField(
            model_name='stingdevice',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Diagnostic'),
        ),
        migrations.AddField(
            model_name='stinginsertion',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.ConditionInstance'),
        ),
        migrations.AddField(
            model_name='stinginsertion',
            name='devices',
            field=models.ManyToManyField(blank=True, to='system.StingDevice'),
        ),
        migrations.AddField(
            model_name='stinginsertion',
            name='duration',
            field=models.FloatField(default=0, verbose_name='duration [s]'),
        ),
        migrations.AlterField(
            model_name='conditioninstance',
            name='end_time',
            field=models.FloatField(blank=True, null=True, verbose_name='end time (s)'),
        ),
        migrations.AlterField(
            model_name='conditioninstance',
            name='start_time',
            field=models.FloatField(blank=True, null=True, verbose_name='start time (s)'),
        ),
        migrations.DeleteModel(
            name='StingSettings',
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='attachments',
            field=models.ManyToManyField(to='system.SettingAttachment'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='conditions',
            field=models.ManyToManyField(to='system.ConditionInstance'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='diagnostics',
            field=models.ManyToManyField(to='data.Diagnostic'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='disks',
            field=models.ManyToManyField(blank=True, to='system.Disk'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='insertions',
            field=models.ManyToManyField(to='system.StingInsertion'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='nozzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Nozzle'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_operator', to='data.Person'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='principle_investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_principle_investigator', to='data.Person'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='test_engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_test_engineer', to='data.Person'),
        ),
        migrations.AddField(
            model_name='stinginsertion',
            name='arm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.StingArm'),
        ),
    ]
