# Generated by Django 2.1.11 on 2020-11-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20201106_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('W', 'Tungsten'), ('AgP', 'SilverPlus'), ('Cu', 'Copper')], default='AgP', max_length=3)),
                ('installed', models.DateField(blank=True, null=True)),
                ('removed', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pretest_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('posttest_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='cathode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Cathode'),
        ),
    ]
