# Generated by Django 2.1.7 on 2019-11-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_cathode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatersettings',
            name='total_cathode_time',
        ),
        migrations.AddField(
            model_name='heatersettings',
            name='cathode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Cathode'),
        ),
    ]
