# Generated by Django 2.1.7 on 2019-11-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20191101_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathode',
            name='posttest_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cathode',
            name='pretest_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cathode',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
