# Generated by Django 2.1.11 on 2020-11-07 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20201106_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerunsettings',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='prerunsettings',
            name='insertions',
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='run_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.PreRunSettings'),
        ),
        migrations.AddField(
            model_name='prerunsettings',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
