# Generated by Django 2.1.11 on 2020-11-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20201106_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditioninstance',
            name='run_settings',
        ),
        migrations.AlterField(
            model_name='stinginsertion',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Condition'),
        ),
    ]
