# Generated by Django 2.1.11 on 2020-11-13 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20201113_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerunsettings',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='prerunsettings',
            name='cathode',
        ),
        migrations.RemoveField(
            model_name='prerunsettings',
            name='diagnostics',
        ),
        migrations.RemoveField(
            model_name='prerunsettings',
            name='disks',
        ),
        migrations.RemoveField(
            model_name='prerunsettings',
            name='nozzle',
        ),
        migrations.RemoveField(
            model_name='prerunsettings',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='prerunsettings',
            name='principle_investigator',
        ),
        migrations.RemoveField(
            model_name='prerunsettings',
            name='test_engineer',
        ),
        migrations.RemoveField(
            model_name='heatersettings',
            name='number_disks',
        ),
        migrations.RemoveField(
            model_name='heatersettings',
            name='total_arc_on_duration',
        ),
        migrations.RemoveField(
            model_name='heatersettings',
            name='total_cathode_time',
        ),
        migrations.AddField(
            model_name='heatersettings',
            name='cathode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Cathode'),
        ),
        migrations.AddField(
            model_name='heatersettings',
            name='disks',
            field=models.ManyToManyField(blank=True, to='system.Disk'),
        ),
        migrations.AlterField(
            model_name='stinginsertion',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.ConditionInstance'),
        ),
        migrations.DeleteModel(
            name='PreRunSettings',
        ),
    ]
