# Generated by Django 2.1.11 on 2020-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20201113_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nozzle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
