# Generated by Django 2.1.11 on 2020-11-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20201119_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoattachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
