# Generated by Django 2.1.11 on 2020-11-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_photoattachment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatersettings',
            name='cathode',
        ),
        migrations.RemoveField(
            model_name='heatersettings',
            name='disks',
        ),
        migrations.RemoveField(
            model_name='heatersettings',
            name='nozzle',
        ),
        migrations.RemoveField(
            model_name='heatersettings',
            name='run',
        ),
        migrations.RemoveField(
            model_name='photoattachment',
            name='run',
        ),
        migrations.RemoveField(
            model_name='stinginsertion',
            name='arm',
        ),
        migrations.RemoveField(
            model_name='stinginsertion',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='stinginsertion',
            name='devices',
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='l1_devices',
            field=models.ManyToManyField(blank=True, related_name='l1_devices', to='system.StingDevice'),
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='l1_insertion',
            field=models.FloatField(blank=True, null=True, verbose_name='dwell time (s)'),
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='l2_devices',
            field=models.ManyToManyField(blank=True, related_name='l2_devices', to='system.StingDevice'),
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='l2_insertion',
            field=models.FloatField(blank=True, null=True, verbose_name='dwell time (s)'),
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='sweep_devices',
            field=models.ManyToManyField(blank=True, related_name='sweep_devices', to='system.StingDevice'),
        ),
        migrations.AddField(
            model_name='conditioninstance',
            name='sweep_insertion',
            field=models.FloatField(blank=True, null=True, verbose_name='dwell time (s)'),
        ),
        migrations.DeleteModel(
            name='HeaterSettings',
        ),
        migrations.DeleteModel(
            name='PhotoAttachment',
        ),
        migrations.DeleteModel(
            name='StingInsertion',
        ),
    ]
