# Generated by Django 2.1.11 on 2020-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20201119_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingattachment',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
