# Generated by Django 2.1.11 on 2020-12-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_settingattachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzle',
            name='installed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conditioninstance',
            name='l1_insertion',
            field=models.FloatField(blank=True, null=True, verbose_name='L1 arm dwell time (s)'),
        ),
        migrations.AlterField(
            model_name='conditioninstance',
            name='l2_insertion',
            field=models.FloatField(blank=True, null=True, verbose_name='L2 arm dwell time (s)'),
        ),
        migrations.AlterField(
            model_name='conditioninstance',
            name='sweep_insertion',
            field=models.FloatField(blank=True, null=True, verbose_name='Sweep arm dwell time (s)'),
        ),
        migrations.AlterField(
            model_name='settingattachment',
            name='type',
            field=models.CharField(choices=[('DOC', 'Document'), ('IMG', 'Image'), ('VID', 'Video'), ('DAT', 'Data'), ('OTR', 'Other')], default='DOC', max_length=3),
        ),
    ]
