# Generated by Django 2.1.11 on 2020-12-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_auto_20201202_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathode',
            name='type',
            field=models.CharField(choices=[('W', 'Tungsten'), ('Ag+', 'SilverPlus'), ('Cu', 'Copper')], default='Ag+', max_length=3),
        ),
    ]
