# Generated by Django 2.1.11 on 2020-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20201204_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasettings',
            name='record_type',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Still', 'Still')], max_length=5, null=True),
        ),
    ]
