# Generated by Django 2.1.11 on 2020-12-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_camerasettings_record_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditioninstance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='conditioninstance',
            name='start_time',
        ),
    ]
