# Generated by Django 2.1.11 on 2020-12-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_auto_20201211_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='disks',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
