# Generated by Django 2.1.11 on 2021-02-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_conditioninstance_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileattachments',
            name='run',
        ),
        migrations.DeleteModel(
            name='FileAttachments',
        ),
    ]
