# Generated by Django 2.1.11 on 2021-03-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20210211_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditioninstance',
            options={'ordering': ['run__date']},
        ),
        migrations.RenameField(
            model_name='cathode',
            old_name='posttest_photo',
            new_name='postremoval_photo',
        ),
        migrations.RenameField(
            model_name='cathode',
            old_name='pretest_photo',
            new_name='preinstall_photo',
        ),
    ]
