# Generated by Django 2.1.11 on 2021-04-13 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20210310_1504'),
        ('system', '0028_auto_20210310_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateComponentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('INPUT', 'Exp Input'), ('OUTPUT', 'Exp Output'), ('ENVIRN', 'Environmental'), ('OTHER', 'Other')], default='OUTPUT', max_length=6)),
                ('value', models.FloatField(blank=True, null=True)),
                ('critical', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('installed', models.DateTimeField(blank=True, null=True)),
                ('removed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('DOC', 'Document'), ('IMG', 'Image'), ('VID', 'Video'), ('OTR', 'Other')], default='DOC', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbrv', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('ionization_energy', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Apparatus')),
            ],
        ),
        migrations.CreateModel(
            name='SubsystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Subsystem')),
            ],
        ),
        migrations.CreateModel(
            name='SubsystemConfigItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=25)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Component')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.SubsystemConfig')),
                ('diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='TestSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('shape', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
                ('diagnostics', models.ManyToManyField(to='data.Diagnostic')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Material')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subsystemconfigitem',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TestSample'),
        ),
        migrations.AddField(
            model_name='component',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Subsystem'),
        ),
        migrations.AddField(
            model_name='alternatecomponentname',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Component'),
        ),
    ]
