# Generated by Django 2.1.11 on 2021-04-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '__first__'),
        ('system', '0029_auto_20210413_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsystemItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('val1_name', models.CharField(max_length=200)),
                ('val2_name', models.CharField(max_length=200)),
                ('val1_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='val1_unit', to='units.ComboUnit')),
                ('val2_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='val2_unit', to='units.ComboUnit')),
            ],
        ),
        migrations.AlterField(
            model_name='subsystemconfigitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.SubsystemItemType'),
        ),
    ]
