# Generated by Django 2.1.11 on 2021-04-19 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '__first__'),
        ('system', '0030_auto_20210414_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='category',
        ),
        migrations.RemoveField(
            model_name='component',
            name='value',
        ),
        migrations.AddField(
            model_name='subsystemconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsystemconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsystemconfig',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subsystemconfigitem',
            name='related_configs',
            field=models.ManyToManyField(blank=True, related_name='related_configs', to='system.SubsystemConfig'),
        ),
        migrations.AddField(
            model_name='subsystemconfigitem',
            name='value3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsystemconfigitem',
            name='value4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsystemitemtype',
            name='val3_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsystemitemtype',
            name='val3_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='val3_unit', to='units.ComboUnit'),
        ),
        migrations.AddField(
            model_name='subsystemitemtype',
            name='val4_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsystemitemtype',
            name='val4_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='val4_unit', to='units.ComboUnit'),
        ),
    ]
