# Generated by Django 2.1.11 on 2021-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_auto_20210419_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
