# Generated by Django 2.1.11 on 2021-04-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystemconfig',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
