# Generated by Django 2.1.11 on 2021-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_subsystemconfig_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystemitemtype',
            name='val1_unit',
        ),
        migrations.RemoveField(
            model_name='subsystemitemtype',
            name='val2_unit',
        ),
        migrations.RemoveField(
            model_name='subsystemitemtype',
            name='val3_unit',
        ),
        migrations.RemoveField(
            model_name='subsystemitemtype',
            name='val4_unit',
        ),
        migrations.AlterField(
            model_name='subsystemconfigitem',
            name='type',
            field=models.CharField(default='water cooling', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubsystemItemType',
        ),
    ]
