# Generated by Django 2.1.11 on 2021-04-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '__first__'),
        ('system', '0034_auto_20210422_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternatecomponentname',
            name='component',
        ),
        migrations.RemoveField(
            model_name='subsystemconfigitem',
            name='related_configs',
        ),
        migrations.RemoveField(
            model_name='subsystemconfigitem',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='subsystemconfigitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subsystemconfigitem',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='subsystemconfigitem',
            name='value4',
        ),
        migrations.AddField(
            model_name='subsystemconfigitem',
            name='value1_name',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsystemconfigitem',
            name='value1_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='val1unit', to='units.ComboUnit'),
        ),
        migrations.AddField(
            model_name='subsystemconfigitem',
            name='value2_name',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsystemconfigitem',
            name='value2_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='val2unit', to='units.ComboUnit'),
        ),
        migrations.DeleteModel(
            name='AlternateComponentName',
        ),
    ]
