# Generated by Django 2.1.1 on 2018-09-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateDiagnosticName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlternateUnitName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apparatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sensor', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resolution', models.FloatField(blank=True, null=True)),
                ('noise', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(null=True)),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Apparatus')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_index', models.IntegerField(blank=True, null=True)),
                ('end_index', models.IntegerField(blank=True, null=True)),
                ('avg_current', models.FloatField(blank=True, null=True)),
                ('std_current', models.FloatField(blank=True, null=True)),
                ('avg_voltage', models.FloatField(blank=True, null=True)),
                ('avg_plasma_gas', models.FloatField(blank=True, null=True)),
                ('avg_shield_gas', models.FloatField(blank=True, null=True)),
                ('avg_chamber_pressure', models.FloatField(blank=True, null=True)),
                ('avg_column_pressure', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Experiment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RunAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Diagnostic')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Series'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Unit'),
        ),
        migrations.AddField(
            model_name='apparatus',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Facility'),
        ),
        migrations.AddField(
            model_name='alternateunitname',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Unit'),
        ),
        migrations.AddField(
            model_name='alternatediagnosticname',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Diagnostic'),
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('name', 'experiment')},
        ),
    ]
