# Generated by Django 2.1.1 on 2018-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='acronym',
            field=models.CharField(default='IHF', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='acronym',
            field=models.CharField(default='IHF', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
