# Generated by Django 2.1.1 on 2018-09-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180928_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apparatus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Apparatus'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='apparatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.Apparatus'),
            preserve_default=False,
        ),
    ]
