# Generated by Django 2.1.1 on 2018-10-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180928_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apparatus',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Apparatus'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='record',
            name='index',
            field=models.IntegerField(editable=False),
        ),
    ]
