# Generated by Django 2.1 on 2018-09-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180906_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='spreadsheet',
            options={'ordering': ['date']},
        ),
    ]
