# Generated by Django 2.1 on 2018-09-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180910_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sensor', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resolution', models.FloatField()),
                ('noise', models.FloatField()),
            ],
        ),
    ]
