# Generated by Django 2.1.7 on 2019-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190221_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='stingdevice',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
