# Generated by Django 2.1.7 on 2019-02-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('data', '0005_stingdevice_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiment',
            new_name='Test',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='experiment',
            new_name='test',
        ),
        migrations.AlterField(
            model_name='run',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('name', 'test')},
        ),
    ]
