# Generated by Django 2.1 on 2018-09-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='noise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='resolution',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
