# Generated by Django 2.1 on 2018-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180910_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
