# Generated by Django 2.1.7 on 2019-02-21 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190221_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('dwell_time', models.FloatField(default=200)),
                ('current', models.FloatField(default=40)),
                ('main_gas_flow', models.FloatField(default=0)),
                ('shield_gas_flow', models.FloatField(default=0)),
                ('purge_gas_flow', models.FloatField(default=0)),
                ('nozzle_distance', models.FloatField(default=6)),
                ('swivel_sting_duration', models.FloatField(default=0)),
                ('L1_sting_duration', models.FloatField(default=0)),
                ('L2_sting_duration', models.FloatField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run')),
            ],
        ),
        migrations.RemoveField(
            model_name='runaggregate',
            name='user',
        ),
    ]
