# Generated by Django 2.1.7 on 2019-02-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190221_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_sheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='condition',
            name='L1_sting_duration',
            field=models.FloatField(default=0, verbose_name='L1 sting duration (s)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='L2_sting_duration',
            field=models.FloatField(default=0, verbose_name='L2 sting duration (s)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='current',
            field=models.FloatField(default=40, verbose_name='Current (A)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='dwell_time',
            field=models.FloatField(default=200, verbose_name='dwell time (s)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='main_gas_flow',
            field=models.FloatField(default=0, verbose_name='main gas flow (g/s)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='nozzle_distance',
            field=models.FloatField(default=6, verbose_name='nozzle distance (cm)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='purge_gas_flow',
            field=models.FloatField(default=0, verbose_name='purge gas flow (g/s)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='shield_gas_flow',
            field=models.FloatField(default=0, verbose_name='shield gas flow (g/s)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='swivel_sting_duration',
            field=models.FloatField(default=0, verbose_name='swivel sting duration (s)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='nozzle_exit_diameter',
            field=models.FloatField(null=True, verbose_name='nozzle exit diameter (cm)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='total_arc_on_duration',
            field=models.FloatField(null=True, verbose_name='total arc-on duration (s)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='total_cathode_time',
            field=models.FloatField(null=True, verbose_name='total cathode time (s)'),
        ),
    ]
