# Generated by Django 2.1.1 on 2018-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_diagnostic_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='sheet',
            name='end_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
