# Generated by Django 2.1.7 on 2019-02-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190222_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='run',
        ),
        migrations.RemoveField(
            model_name='runaggregate',
            name='run',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='run',
            name='L1_sting_arm',
        ),
        migrations.RemoveField(
            model_name='run',
            name='L2_sting_arm',
        ),
        migrations.RemoveField(
            model_name='run',
            name='main_gas',
        ),
        migrations.RemoveField(
            model_name='run',
            name='nozzle_exit_diameter',
        ),
        migrations.RemoveField(
            model_name='run',
            name='number_cathode_starts',
        ),
        migrations.RemoveField(
            model_name='run',
            name='number_disks',
        ),
        migrations.RemoveField(
            model_name='run',
            name='posttest_photo',
        ),
        migrations.RemoveField(
            model_name='run',
            name='pretest_photo',
        ),
        migrations.RemoveField(
            model_name='run',
            name='purge_gas',
        ),
        migrations.RemoveField(
            model_name='run',
            name='run_sheet',
        ),
        migrations.RemoveField(
            model_name='run',
            name='shield_gas',
        ),
        migrations.RemoveField(
            model_name='run',
            name='swivel_sting_arm',
        ),
        migrations.RemoveField(
            model_name='run',
            name='total_arc_on_duration',
        ),
        migrations.RemoveField(
            model_name='run',
            name='total_cathode_time',
        ),
        migrations.RemoveField(
            model_name='run',
            name='video',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Gas',
        ),
        migrations.DeleteModel(
            name='RunAggregate',
        ),
        migrations.DeleteModel(
            name='StingDevice',
        ),
    ]
