# Generated by Django 2.1.7 on 2019-02-23 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20190222_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparatus',
            name='facility',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
