# Generated by Django 2.1.1 on 2018-09-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180926_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='std_current',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
