# Generated by Django 2.1.7 on 2019-09-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20190223_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
