# Generated by Django 2.1.1 on 2018-09-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_sheet_std_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='avg_chamber_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='avg_column_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
