# Generated by Django 2.1.7 on 2019-09-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20190917_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatediagnosticname',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
