# Generated by Django 2.1.7 on 2019-11-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_cathode'),
        ('data', '0012_auto_20190917_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='cathode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Cathode'),
        ),
    ]
