# Generated by Django 2.1.1 on 2018-09-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_apparatus_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Facility'),
        ),
    ]
