# Generated by Django 2.2.5 on 2019-12-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20191212_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
