# Generated by Django 2.1.11 on 2020-10-29 21:48

from django.db import migrations
import numpy as np

def copySeries_to_DiagnosticSeries(apps, schema_editor):
    DiagnosticSeries = apps.get_model('data',"DiagnosticSeries")
    Series = apps.get_model('data',"Series")
    Record = apps.get_model('data',"Record")
    TimeSeries = apps.get_model('data', "TimeSeries")
    Run = apps.get_model('data',"Run")

    for r in Run.objects.all():
        ts = Series.objects.filter(run=r, diagnostic__name="Time [s]")[0]
        time = np.array(ts.record_set.order_by('index').values_list('value',flat=True))
        ts = TimeSeries(time=time)
        ts.save()

        series = Series.objects.filter(run=r).exclude(diagnostic__name="Time [s]")
        for s in series:
            vlist = s.record_set.order_by('index').values_list('value',flat=True)
            vals = np.array( vlist, dtype=float )
            
            ds = DiagnosticSeries(diagnostic = s.diagnostic,
                                run = r,
                                name = s.name,
                                time = ts,
                                values = vals)
            ds.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20201029_1444'),
    ]

    operations = [
        migrations.RunPython(copySeries_to_DiagnosticSeries)
    ]
