# Generated by Django 2.1.7 on 2019-11-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_run_cathode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='cathode',
        ),
    ]
