# Generated by Django 2.2.5 on 2019-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20191212_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
