# Generated by Django 2.1.11 on 2020-11-06 22:29

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20201029_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCalibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinput', data.models.MyArrayField()),
                ('output', data.models.MyArrayField()),
                ('resolution', models.FloatField(blank=True, null=True)),
                ('temporalresolution', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('expiration', models.DateField(null=True)),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('DOC', 'Document'), ('IMG', 'Image'), ('VID', 'Video'), ('OTR', 'Other')], default='DOC', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'diagnostic files',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='noise',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='resolution',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='diagnosticsetup',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Diagnostic'),
        ),
        migrations.AddField(
            model_name='diagnosticfile',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Diagnostic'),
        ),
        migrations.AddField(
            model_name='diagnosticfile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run'),
        ),
        migrations.AddField(
            model_name='diagnosticcalibration',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Diagnostic'),
        ),
        migrations.AddField(
            model_name='diagnosticcalibration',
            name='inputUnits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Unit'),
        ),
    ]
