# Generated by Django 2.1.11 on 2020-11-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20201106_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='diagnostics',
            field=models.ManyToManyField(to='data.Diagnostic'),
        ),
    ]
