# Generated by Django 2.1.11 on 2020-11-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20201113_1553'),
        ('data', '0016_run_diagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='cathode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Cathode'),
        ),
        migrations.AddField(
            model_name='run',
            name='disks',
            field=models.ManyToManyField(blank=True, to='system.Disk'),
        ),
        migrations.AddField(
            model_name='run',
            name='nozzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Nozzle'),
        ),
        migrations.AlterField(
            model_name='run',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
