# Generated by Django 2.1.11 on 2020-12-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20201119_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='series',
        ),
        migrations.RemoveField(
            model_name='series',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='series',
            name='run',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
