# Generated by Django 2.1.11 on 2020-12-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20201204_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='flag',
            field=models.CharField(blank=True, choices=[('FAILED', 'Failed'), ('OFF-NOMINAL', 'Off-nominal'), ('SUCCESS', 'Success'), ('PRERUN', 'Pre-run')], max_length=12, null=True),
        ),
    ]
