# Generated by Django 2.1.11 on 2021-02-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_run_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='flags',
        ),
    ]
