# Generated by Django 2.1.11 on 2021-03-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_run_flags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-date']},
        ),
    ]
