# Generated by Django 2.1.11 on 2021-03-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20210301_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='category',
            field=models.CharField(choices=[('INPUT', 'Exp Input'), ('OUTPUT', 'Exp Output'), ('ENVIRN', 'Environmental'), ('OTHER', 'Other')], default='OUTPUT', max_length=6),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='flag_if_missing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
