# Generated by Django 2.1.11 on 2021-04-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20210310_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='category',
            field=models.CharField(choices=[('INPUT', 'Exp Input'), ('OUTPUT', 'Exp Output'), ('ENVIRN', 'Environmental'), ('CAMERA', 'Camera'), ('OTHER', 'Other')], default='OUTPUT', max_length=6),
        ),
    ]
