# Generated by Django 2.1.11 on 2021-04-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20210421_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.ComboUnit'),
        ),
    ]
