# Generated by Django 2.1.11 on 2020-12-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('length_dim', models.IntegerField()),
                ('mass_dim', models.IntegerField()),
                ('time_dim', models.IntegerField()),
                ('current_dim', models.IntegerField()),
                ('temp_dim', models.IntegerField()),
                ('mole_dim', models.IntegerField()),
                ('luminous_dim', models.IntegerField()),
                ('length_ratio', models.FloatField()),
                ('mass_ratio', models.FloatField()),
                ('time_ratio', models.FloatField()),
                ('current_ratio', models.FloatField()),
                ('mole_ratio', models.FloatField()),
                ('luminous_ratio', models.FloatField()),
                ('temp_ratio', models.FloatField()),
                ('temp_offset', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComboUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('baseunits', models.ManyToManyField(to='units.BaseUnit')),
                ('memberunits', models.ManyToManyField(to='units.ComboUnit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
