# Generated by Django 2.1.11 on 2020-12-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combounit',
            name='baseunits',
        ),
        migrations.RemoveField(
            model_name='combounit',
            name='memberunits',
        ),
        migrations.DeleteModel(
            name='ComboUnit',
        ),
    ]
