# Generated by Django 2.1.11 on 2020-12-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20201218_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnitPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComboUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('memberunits', models.ManyToManyField(to='units.BaseUnitPower')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='current_dim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='current_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='length_dim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='length_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='luminous_dim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='luminous_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='mass_dim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='mass_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='mole_dim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='mole_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='temp_dim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='temp_offset',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='temp_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='time_dim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='time_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baseunitpower',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.BaseUnit'),
        ),
    ]
