# Generated by Django 2.1.11 on 2020-12-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20201221_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combounit',
            name='memberunits',
        ),
        migrations.AddField(
            model_name='baseunitpower',
            name='combo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='units.ComboUnit'),
            preserve_default=False,
        ),
    ]
