# Generated by Django 2.1.11 on 2020-12-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20201221_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseunit',
            name='coeff',
            field=models.FloatField(default=1),
        ),
    ]
