# Generated by Django 2.1.11 on 2020-12-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_baseunit_coeff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseunit',
            name='current_ratio',
        ),
        migrations.RemoveField(
            model_name='baseunit',
            name='length_ratio',
        ),
        migrations.RemoveField(
            model_name='baseunit',
            name='luminous_ratio',
        ),
        migrations.RemoveField(
            model_name='baseunit',
            name='mass_ratio',
        ),
        migrations.RemoveField(
            model_name='baseunit',
            name='mole_ratio',
        ),
        migrations.RemoveField(
            model_name='baseunit',
            name='temp_ratio',
        ),
        migrations.RemoveField(
            model_name='baseunit',
            name='time_ratio',
        ),
    ]
