# Generated by Django 2.1.7 on 2019-11-01 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0009_auto_20191031_1734'),
        ('data', '0012_auto_20190917_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.FloatField(blank=True, null=True)),
                ('stdev', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Diagnostic')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ConditionInstance')),
            ],
        ),
    ]
