# Generated by Django 2.1.11 on 2020-12-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0019_auto_20201204_1551'),
        ('system', '0020_auto_20201204_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionInstanceFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField(blank=True, null=True)),
                ('stable_start', models.FloatField(blank=True, null=True)),
                ('stable_end', models.FloatField(blank=True, null=True)),
                ('end', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.ConditionInstance')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesStableStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.FloatField(blank=True, null=True)),
                ('stdev', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ConditionInstance')),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.DiagnosticSeries')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesStartupStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.FloatField(blank=True, null=True)),
                ('stdev', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ConditionInstance')),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.DiagnosticSeries')),
            ],
        ),
    ]
