# Generated by Django 2.1.11 on 2019-12-12 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0013_auto_20191212_1520'),
        ('system', '0009_auto_20191212_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Run')),
            ],
        ),
        migrations.CreateModel(
            name='IHFAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=15, null=True)),
                ('calsize', models.FloatField(blank=True, null=True, verbose_name='CalSize [in]')),
                ('standoff_dist', models.FloatField(blank=True, null=True, verbose_name='Distance from NEP [in]')),
                ('winovich', models.FloatField(blank=True, null=True, verbose_name='Winovich Sonic Enthalpy [MJ/kg]')),
                ('shepard', models.FloatField(blank=True, null=True, verbose_name='Shepard Sonic Enthalpy [MJ/kg]')),
                ('eb2', models.FloatField(blank=True, null=True, verbose_name='EB2 [MJ/kg]')),
                ('eb2err', models.FloatField(blank=True, null=True, verbose_name='EB2 err [%]')),
                ('dt41', models.FloatField(blank=True, null=True, verbose_name='DT41_0 [degC]')),
                ('dt41set', models.FloatField(blank=True, null=True, verbose_name='DT41_0 set to [degC]')),
                ('arcEff', models.FloatField(blank=True, null=True, verbose_name='Winovich Sonic Enthalpy [MJ/kg]')),
                ('hcenterline', models.FloatField(blank=True, null=True, verbose_name='h_centerline [MJ/kg]')),
                ('qcenter', models.FloatField(blank=True, null=True, verbose_name='q_center [W/cm^2]')),
                ('Pt2', models.FloatField(blank=True, null=True, verbose_name='P_t2 [kPa]')),
                ('arcpressure', models.FloatField(blank=True, null=True, verbose_name='Arc pressure [kPa]')),
                ('arccurrent', models.FloatField(blank=True, null=True, verbose_name='Arc current [A]')),
                ('arcvoltage', models.FloatField(blank=True, null=True, verbose_name='Arc voltage [V]')),
                ('mainair', models.FloatField(blank=True, null=True, verbose_name='Main air [g/s]')),
                ('addair', models.FloatField(blank=True, null=True, verbose_name='Add air [g/s]')),
                ('argon', models.FloatField(blank=True, null=True, verbose_name='Argon [g/s]')),
                ('reff', models.FloatField(blank=True, null=True, verbose_name='R_eff [cm]')),
                ('qreff', models.FloatField(blank=True, null=True, verbose_name='qR_eff [W/cm^1.5]')),
                ('comments', models.TextField(blank=True, null=True)),
                ('tstart', models.FloatField(blank=True, null=True, verbose_name='Start time [s]')),
                ('tend', models.FloatField(blank=True, null=True, verbose_name='End time [s]')),
                ('boxpressure', models.FloatField(blank=True, null=True, verbose_name='Box pressure [kPa]')),
                ('arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.StingArm')),
                ('calshape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.CalShape')),
                ('caltype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.CalType')),
                ('nozzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Nozzle')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Run')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Test')),
            ],
        ),
    ]
