# Generated by Django 2.1.11 on 2020-12-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20201204_1551'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionInstanceFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, choices=[('FAILED', 'Failed'), ('OFF-NOMINAL', 'Off-nominal'), ('SUCCESS', 'Success'), ('OTHER', 'Other')], max_length=12, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ConditionInstance')),
            ],
        ),
    ]
