# Generated by Django 2.2.5 on 2019-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20191212_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihfaggregate',
            name='plenum',
            field=models.BooleanField(default=True),
        ),
    ]
