# Generated by Django 2.1.11 on 2020-12-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20201208_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesstablestats',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DiagnosticSeries'),
        ),
        migrations.AlterField(
            model_name='seriesstartupstats',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DiagnosticSeries'),
        ),
    ]
