# Generated by Django 2.1.11 on 2020-12-16 19:48

import data.models
from django.db import migrations, models
import django.db.models.deletion
import stats.models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_run_flag'),
        ('stats', '0004_auto_20201208_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('headers', stats.models.MyListField(blank=True, null=True)),
                ('coeff', data.models.MyArrayField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(null=True)),
                ('diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Diagnostic')),
            ],
        ),
    ]
