# Generated by Django 2.1.11 on 2020-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_linearmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearmodel',
            name='fit_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
