# Generated by Django 2.1.11 on 2021-02-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_run_flags'),
        ('stats', '0008_flag_runusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flag',
        ),
    ]
