# Generated by Django 2.1.11 on 2021-03-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_delete_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rating', models.PositiveIntegerField(choices=[(0, 'Missing diagnostic'), (1, 'Missing input diagnostic'), (2, 'Run aborted')], default=0)),
            ],
        ),
    ]
