# Generated by Django 2.1.11 on 2021-03-11 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20210310_1504'),
        ('stats', '0010_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='name',
        ),
        migrations.AddField(
            model_name='flag',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.Run'),
            preserve_default=False,
        ),
    ]
